### ISSUE TITLE
Add option to also sort on the canvas

### ISSUE THREAD

**Issue by miguelsolorio** [kawamurakazushi/figma-sort-it#2]
While sorting in the layers is very handy, I would love to be able to sort the layers on the canvas as well. I would expect that it would re-arrange them using either the same spacing used or provide a margin.

**Comment by kawamurakazushi** [comment]
@misolori Thanks for opening an issue! 
As said in the Figma Plugin Slack, Figma Format should do the a similar job. It will sort the layers plus re-arrange the canvas. 

I want to keep this plugin as simple as possible, so I will close this issue!
If there's any other problem, please feel free to open another issue!
