### ISSUE TITLE
Components with capitals do not sort correctly

### ISSUE THREAD

**Issue by rdimascio** [kawamurakazushi/figma-sort-it#5]
![2020-07-07 13 39 29](https://user-images.githubusercontent.com/17639082/86840496-9e5ffd00-c057-11ea-814a-6e19fb00f2d4.gif)

### Expected Behavior:

The expected behavior is to sort A-Z: Adobe, AWS, Chrome, CSS, Webpack, WebStorm.

### Actual Behavior:

The actual behavior is that the frames with capital letters in any part of the string get sorted ahead of frames with lowercase: AWS, Adobe, CSS, Chrome, WebStorm, Webpack.

**Comment by kawamurakazushi** [comment]
@rdimascio Published 👍
